name: Deploy Flet App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Flet
        run: |
          pip install flet==0.85.3

      - name: Build Web Static Files
        run: |
          yes | flet build web --module-name home --web-renderer html
          sed -i 's|<base href="/">|<base href="./">|g' build/web/index.html
          
          # Flet වල JavaScript එක බ්‍රවුසර් එකෙන් බ්ලොක් කරන ලෙඩේ සුව කිරීම:
          sed -i 's|<base href="/">|<base href="./">|g' build/web/index.html
          sed -i 's|type="text/javascript"|type="application/javascript"|g' build/web/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages