name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Install Flet
        run: |
          pip install flet
          flet --version
      
      - name: Build web app
        run: |
          export FLUTTER_ROOT=/opt/hostedtoolcache/flutter/stable-3.24.0-x64
          export PATH="$FLUTTER_ROOT/bin:$PATH"
          flet build web --base-url /sahanmadhushanka.github.io --route-url-strategy hash
      
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          force_orphan: true